/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycalculator;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.BadLocationException;

/**
 *
 * @author szyos
 */
public class Calc extends JDialog {

    double firstNumber;
    double secondNumber;
    double result;
    String operation;
    double roundOff;
    
    
        
    /**
     * Creates new form Calc
     */
    public Calc() {
        
        initComponents();
//        enableFalse();
        this.setAlwaysOnTop(true);
        deleteBacklight(addition);
        deleteBacklight(button0);
        deleteBacklight(button1);
        deleteBacklight(button2);
        deleteBacklight(button3);
        deleteBacklight(button4);
        deleteBacklight(button5);
        deleteBacklight(button6);
        deleteBacklight(button7);
        deleteBacklight(button8);
        deleteBacklight(cButton);
        deleteBacklight(ceButton);
        deleteBacklight(calculation);
        deleteBacklight(comma);
        deleteBacklight(delButton);
        deleteBacklight(division);
        deleteBacklight(multiplication);
        deleteBacklight(percent);
        deleteBacklight(raising);
        deleteBacklight(root);
        deleteBacklight(sign);
        deleteBacklight(substraction);
        deleteBacklight(button9);
        
        
    }

    public void enableFalse()
    {
//        root.setEnabled(false);
//        percent.setEnabled(false);
//        raising.setEnabled(false);
//        division.setEnabled(false);
//        multiplication.setEnabled(false);
//        substraction.setEnabled(false);
//        addition.setEnabled(false);
//        calculation.setEnabled(false);
    }
    public void enableTrue()
    {
        root.setEnabled(true);
        percent.setEnabled(true);
        raising.setEnabled(true);
        division.setEnabled(true);
        multiplication.setEnabled(true);
        substraction.setEnabled(true);
        addition.setEnabled(true);
       
    }
    public void deleteBacklight(JButton button)
    {
        button.setFocusPainted(false);
        button.setContentAreaFilled(false);
        button.setOpaque(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        percent = new javax.swing.JButton();
        root = new javax.swing.JButton();
        raising = new javax.swing.JButton();
        division = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        substraction = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        calculation = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        comma = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        sign = new javax.swing.JButton();
        ceButton = new javax.swing.JButton();
        textArea = new javax.swing.JTextField();
        textArea1 = new javax.swing.JTextField();

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setAutoscrolls(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KALKULATOR");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        percent.setBackground(new java.awt.Color(166, 166, 166));
        percent.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        percent.setText("%");
        percent.setBorder(null);
        percent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        percent.setFocusPainted(false);
        percent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                percentFocusGained(evt);
            }
        });
        percent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                percentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                percentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                percentMousePressed(evt);
            }
        });
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentActionPerformed(evt);
            }
        });
        percent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                percentKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                percentKeyTyped(evt);
            }
        });

        root.setBackground(new java.awt.Color(166, 166, 166));
        root.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        root.setText("√");
        root.setBorder(null);
        root.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        root.setFocusPainted(false);
        root.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rootMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rootMouseExited(evt);
            }
        });
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        raising.setBackground(new java.awt.Color(166, 166, 166));
        raising.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        raising.setText("^");
        raising.setBorder(null);
        raising.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        raising.setFocusPainted(false);
        raising.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raisingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raisingMouseExited(evt);
            }
        });
        raising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raisingActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(255, 149, 1));
        division.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        division.setForeground(new java.awt.Color(255, 255, 255));
        division.setText("/");
        division.setBorder(null);
        division.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        division.setFocusPainted(false);
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divisionMouseExited(evt);
            }
        });
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        multiplication.setBackground(new java.awt.Color(255, 149, 1));
        multiplication.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        multiplication.setForeground(new java.awt.Color(255, 255, 255));
        multiplication.setText("×");
        multiplication.setBorder(null);
        multiplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        multiplication.setFocusPainted(false);
        multiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplicationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplicationMouseExited(evt);
            }
        });
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationActionPerformed(evt);
            }
        });

        substraction.setBackground(new java.awt.Color(255, 149, 1));
        substraction.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        substraction.setForeground(new java.awt.Color(255, 255, 255));
        substraction.setText("-");
        substraction.setBorder(null);
        substraction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        substraction.setFocusPainted(false);
        substraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                substractionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                substractionMouseExited(evt);
            }
        });
        substraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractionActionPerformed(evt);
            }
        });

        addition.setBackground(new java.awt.Color(255, 149, 1));
        addition.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addition.setForeground(new java.awt.Color(255, 255, 255));
        addition.setText("+");
        addition.setBorder(null);
        addition.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addition.setFocusPainted(false);
        addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                additionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                additionMouseExited(evt);
            }
        });
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });

        calculation.setBackground(new java.awt.Color(255, 149, 1));
        calculation.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        calculation.setForeground(new java.awt.Color(255, 255, 255));
        calculation.setText("=");
        calculation.setBorder(null);
        calculation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calculation.setFocusPainted(false);
        calculation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculationMouseExited(evt);
            }
        });
        calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(166, 166, 166));
        delButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        delButton.setText("D");
        delButton.setBorder(null);
        delButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delButton.setFocusPainted(false);
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delButtonMouseExited(evt);
            }
        });
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(51, 51, 51));
        button9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setText("9");
        button9.setBorder(null);
        button9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button9.setFocusPainted(false);
        button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button9MouseExited(evt);
            }
        });
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(51, 51, 51));
        button6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setText("6");
        button6.setBorder(null);
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button6.setFocusPainted(false);
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button6MouseExited(evt);
            }
        });
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(51, 51, 51));
        button3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("3");
        button3.setBorder(null);
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.setFocusPainted(false);
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button3MouseExited(evt);
            }
        });
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        comma.setBackground(new java.awt.Color(51, 51, 51));
        comma.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        comma.setForeground(new java.awt.Color(255, 255, 255));
        comma.setText(".");
        comma.setBorder(null);
        comma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comma.setFocusPainted(false);
        comma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commaMouseExited(evt);
            }
        });
        comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(51, 51, 51));
        button8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setText("8");
        button8.setBorder(null);
        button8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button8.setFocusPainted(false);
        button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button8MouseExited(evt);
            }
        });
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(51, 51, 51));
        button5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setText("5");
        button5.setBorder(null);
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button5.setFocusPainted(false);
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button5MouseExited(evt);
            }
        });
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(51, 51, 51));
        button2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("2");
        button2.setBorder(null);
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button2.setFocusPainted(false);
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button2MouseExited(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button0.setBackground(new java.awt.Color(51, 51, 51));
        button0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button0.setForeground(new java.awt.Color(255, 255, 255));
        button0.setText("0");
        button0.setBorder(null);
        button0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button0.setFocusPainted(false);
        button0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button0MouseMoved(evt);
            }
        });
        button0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button0MouseExited(evt);
            }
        });
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        cButton.setBackground(new java.awt.Color(166, 166, 166));
        cButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cButton.setText("C");
        cButton.setBorder(null);
        cButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cButton.setFocusPainted(false);
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cButtonMouseExited(evt);
            }
        });
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(51, 51, 51));
        button7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setText("7");
        button7.setBorder(null);
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button7.setFocusPainted(false);
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button7MouseExited(evt);
            }
        });
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(51, 51, 51));
        button4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("4");
        button4.setBorder(null);
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button4.setFocusPainted(false);
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button4MouseExited(evt);
            }
        });
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(51, 51, 51));
        button1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("1");
        button1.setBorder(null);
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFocusPainted(false);
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                button1KeyTyped(evt);
            }
        });

        sign.setBackground(new java.awt.Color(51, 51, 51));
        sign.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sign.setForeground(new java.awt.Color(255, 255, 255));
        sign.setText("±");
        sign.setBorder(null);
        sign.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sign.setFocusPainted(false);
        sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signMouseExited(evt);
            }
        });
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });

        ceButton.setBackground(new java.awt.Color(166, 166, 166));
        ceButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ceButton.setText("CE");
        ceButton.setBorder(null);
        ceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ceButton.setFocusPainted(false);
        ceButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ceButtonFocusGained(evt);
            }
        });
        ceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ceButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ceButtonMouseExited(evt);
            }
        });
        ceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceButtonActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textArea.setText("0");
        textArea.setAutoscrolls(false);
        textArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textArea.setCaretColor(new java.awt.Color(255, 0, 0));
        textArea.setMargin(new java.awt.Insets(0, 0, 0, 0));
        textArea.setSelectionColor(new java.awt.Color(102, 102, 102));

        textArea1.setEditable(false);
        textArea1.setBackground(new java.awt.Color(0, 0, 0));
        textArea1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        textArea1.setForeground(new java.awt.Color(255, 255, 255));
        textArea1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textArea1.setAutoscrolls(false);
        textArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textArea1.setCaretColor(new java.awt.Color(255, 0, 0));
        textArea1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        textArea1.setSelectionColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(textArea1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(raising, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(substraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(raising, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(substraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformed
        try
        {
            
            textArea1.setText("");
            enableFalse();
            String answer;
            secondNumber = Double.parseDouble(textArea.getText());
        switch (operation)
        {
            case "+":
                result = firstNumber + secondNumber;
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            case "-":
                result = firstNumber - secondNumber;
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            case "*":
                result = firstNumber * secondNumber;
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            case "/":
                result = firstNumber / secondNumber;
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            case "^":
                result = Math.pow(firstNumber, secondNumber);
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            case "r":
                result = Math.pow(firstNumber, (1/secondNumber));
                roundOff = Math.round(result * 1000.0) / 1000.0;
                answer = ""+roundOff;
                textArea.setText(answer);
                break;
            
        }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_calculationActionPerformed

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        try
        {
        double tmp =  Double.parseDouble(textArea.getText())/100;
        textArea.setText("" + tmp);
        calculation.setEnabled(true);
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_percentActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button2.getText();
        textArea.setText(takein);
       
        enableTrue();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button1.getText();
        textArea.setText(takein);
       
        enableTrue();
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button3.getText();
        
        textArea.setText(takein);
        
        enableTrue();
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button4.getText();
        textArea.setText(takein);
       
        enableTrue();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button5.getText();
        textArea.setText(takein);
        
        enableTrue();
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button6.getText();
        textArea.setText(takein);
      
        enableTrue();
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button7.getText();
        textArea.setText(takein);
       
        enableTrue();
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button8.getText();
        textArea.setText(takein);
       
        enableTrue();
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button9.getText();
        textArea.setText(takein);
      
        enableTrue();
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        zeroRemove();
        String takein;
        takein = textArea.getText() + button0.getText();
        textArea.setText(takein);
      
        enableTrue();
    }//GEN-LAST:event_button0ActionPerformed

    private void commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaActionPerformed
        
         
        String takein;
        textArea.select(textArea.getText().indexOf(".",0), textArea.getText().indexOf(".")+".".length());
        textArea.replaceSelection("");
        if(!textArea.getText().equals(""))
        {
        takein = textArea.getText() + ".";
        textArea.setText(takein); 
        }
       
        
    }//GEN-LAST:event_commaActionPerformed

    private void ceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceButtonActionPerformed
        textArea.setText("0");
        
        enableTrue();
    }//GEN-LAST:event_ceButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        if (textArea.getText().length()==1)
            textArea.setText("0");
        else
        {
            textArea.select(textArea.getText().length()-1, textArea.getText().length());
            textArea.replaceSelection("");
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains(addition.getText()))
            {
            }
            else
            {
                takein = textArea1.getText() + textArea.getText() + addition.getText();
                textArea1.setText(takein);
                firstNumber =  Double.parseDouble(textArea.getText());
                textArea.setText("");
                operation = "+";
                calculation.setEnabled(true);
                
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
                
    }//GEN-LAST:event_additionActionPerformed

    private void substractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractionActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains(substraction.getText()))
            {
            }
            else
            {
                takein = textArea1.getText() + textArea.getText() + substraction.getText();
                textArea1.setText(takein);
                firstNumber =  Double.parseDouble(textArea.getText());
                textArea.setText("");
                operation = "-";
                calculation.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_substractionActionPerformed

    private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains(multiplication.getText()))
            {
            }
            else
            {
            takein = textArea1.getText() + textArea.getText() + multiplication.getText();
            textArea1.setText(takein);
            firstNumber =  Double.parseDouble(textArea.getText());
            textArea.setText("");
            operation = "*";
            calculation.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_multiplicationActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains("➗"))
            {
            }
            else
            {
                takein = textArea1.getText() + textArea.getText() + "➗";
                textArea1.setText(takein);
                firstNumber =  Double.parseDouble(textArea.getText());
                textArea.setText("");
                operation = "/";
                calculation.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_divisionActionPerformed

    private void raisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raisingActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains(raising.getText()))
            {
            }
            else
            {
                takein = textArea1.getText() + textArea.getText() + raising.getText();
                textArea1.setText(takein);
                firstNumber =  Double.parseDouble(textArea.getText());
                textArea.setText("");
                operation = "^";
                calculation.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_raisingActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
        try
        {
            String takein;
            if(textArea1.getText().contains(root.getText()))
            {
            }
            else
            {
                takein = textArea1.getText() + root.getText() + textArea.getText();
                textArea1.setText(takein);
                firstNumber =  Double.parseDouble(textArea.getText());
                textArea.setText("");
                operation = "r";
                calculation.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_rootActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
         
        
        String tmp = textArea.getText();
        
        
        try
        {
            if(!textArea.getText().equals("") || Double.parseDouble(textArea.getText()) == 0)
            {
                tmp = "-"+ textArea.getText();


                textArea.setText(tmp);


            }
            if(textArea.getText().contains("--"))
            {
                textArea.select(textArea.getText().indexOf("--",0), textArea.getText().indexOf("--")+"--".length());
                textArea.replaceSelection("");
               // textArea.setText(tmp);
            }
        }
        catch(NumberFormatException e)
        {
            System.out.println(e.getMessage());
        }
        
        
        
//        if(!textArea.getText().equals(""))
//        {
//        takein = textArea.getText() + ".";
//        textArea.setText(takein); 
//        }
    }//GEN-LAST:event_signActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        
        
       
        textArea.setText("0");
        textArea1.setText("");
        firstNumber = 0;
        secondNumber = 0;
        operation = "";
        result = 0;
        enableFalse();
    }//GEN-LAST:event_cButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setBounds(300, 300, this.getSize().width, this.getSize().height);
    }//GEN-LAST:event_formComponentShown

    private void button1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_button1KeyTyped

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        buttonNumbersColorGained(button1);
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
      
        buttonNumbersColorLost(button1);
    }//GEN-LAST:event_button1MouseExited

    private void button0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MouseEntered
        buttonNumbersColorGained(button0);
    }//GEN-LAST:event_button0MouseEntered

    private void button0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MouseExited
        buttonNumbersColorLost(button0);
    }//GEN-LAST:event_button0MouseExited

    private void button0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MouseMoved
       
    }//GEN-LAST:event_button0MouseMoved

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        buttonNumbersColorGained(button2);
    }//GEN-LAST:event_button2MouseEntered

    private void button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseExited
         buttonNumbersColorLost(button2);
    }//GEN-LAST:event_button2MouseExited

    private void button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseEntered
        buttonNumbersColorGained(button3);
    }//GEN-LAST:event_button3MouseEntered

    private void button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseExited
         buttonNumbersColorLost(button3);
    }//GEN-LAST:event_button3MouseExited

    private void button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseEntered
        buttonNumbersColorGained(button4);
    }//GEN-LAST:event_button4MouseEntered

    private void button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseExited
        buttonNumbersColorLost(button4);
    }//GEN-LAST:event_button4MouseExited

    private void button5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseEntered
       buttonNumbersColorGained(button5);
    }//GEN-LAST:event_button5MouseEntered

    private void button5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseExited
        buttonNumbersColorLost(button5);
    }//GEN-LAST:event_button5MouseExited

    private void button6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseEntered
       buttonNumbersColorGained(button6);
    }//GEN-LAST:event_button6MouseEntered

    private void button6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseExited
        buttonNumbersColorLost(button6);
    }//GEN-LAST:event_button6MouseExited

    private void button7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseEntered
        buttonNumbersColorGained(button7);
    }//GEN-LAST:event_button7MouseEntered

    private void button7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseExited
         buttonNumbersColorLost(button7);
    }//GEN-LAST:event_button7MouseExited

    private void button8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseEntered
       buttonNumbersColorGained(button8);
    }//GEN-LAST:event_button8MouseEntered

    private void button8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseExited
         buttonNumbersColorLost(button8);
    }//GEN-LAST:event_button8MouseExited

    private void button9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseEntered
        buttonNumbersColorGained(button9);
    }//GEN-LAST:event_button9MouseEntered

    private void button9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseExited
         buttonNumbersColorLost(button9);
    }//GEN-LAST:event_button9MouseExited

    private void signMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signMouseEntered
        buttonNumbersColorGained(sign);
    }//GEN-LAST:event_signMouseEntered

    private void signMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signMouseExited
        buttonNumbersColorLost(sign);
    }//GEN-LAST:event_signMouseExited

    private void commaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commaMouseEntered
        buttonNumbersColorGained(comma);
    }//GEN-LAST:event_commaMouseEntered

    private void commaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commaMouseExited
        buttonNumbersColorLost(comma);
    }//GEN-LAST:event_commaMouseExited

    private void calculationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculationMouseEntered
        buttonOperationsColorGained(calculation);
    }//GEN-LAST:event_calculationMouseEntered

    private void calculationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculationMouseExited
        buttonOperationsColorLost(calculation);
    }//GEN-LAST:event_calculationMouseExited

    private void additionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionMouseEntered
        buttonOperationsColorGained(addition);
    }//GEN-LAST:event_additionMouseEntered

    private void additionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionMouseExited
        buttonOperationsColorLost(addition);
    }//GEN-LAST:event_additionMouseExited

    private void substractionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substractionMouseEntered
        buttonOperationsColorGained(substraction);
    }//GEN-LAST:event_substractionMouseEntered

    private void substractionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substractionMouseExited
        buttonOperationsColorLost(substraction);
    }//GEN-LAST:event_substractionMouseExited

    private void multiplicationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationMouseEntered
       buttonOperationsColorGained(multiplication);
    }//GEN-LAST:event_multiplicationMouseEntered

    private void multiplicationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationMouseExited
       buttonOperationsColorLost(multiplication);
    }//GEN-LAST:event_multiplicationMouseExited

    private void delButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseEntered
       buttonColorGained(delButton);
    }//GEN-LAST:event_delButtonMouseEntered

    private void delButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseExited
        buttonColorLost(delButton);
    }//GEN-LAST:event_delButtonMouseExited

    private void cButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseEntered
        buttonColorGained(cButton);
    }//GEN-LAST:event_cButtonMouseEntered

    private void cButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseExited
        buttonColorLost(cButton);
    }//GEN-LAST:event_cButtonMouseExited

    private void ceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceButtonMouseEntered
       buttonColorGained(ceButton);
    }//GEN-LAST:event_ceButtonMouseEntered

    private void ceButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceButtonMouseExited
        buttonColorLost(ceButton);
    }//GEN-LAST:event_ceButtonMouseExited

    private void divisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseEntered
        buttonOperationsColorGained(division);
    }//GEN-LAST:event_divisionMouseEntered

    private void divisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseExited
        buttonOperationsColorLost(division);
    }//GEN-LAST:event_divisionMouseExited

    private void raisingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raisingMouseEntered
       buttonColorGained(raising);
    }//GEN-LAST:event_raisingMouseEntered

    private void raisingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raisingMouseExited
        buttonColorLost(raising);
    }//GEN-LAST:event_raisingMouseExited

    private void rootMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootMouseEntered
        buttonColorGained(root);
    }//GEN-LAST:event_rootMouseEntered

    private void rootMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootMouseExited
        buttonColorLost(root);
    }//GEN-LAST:event_rootMouseExited

    private void percentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentMouseEntered
        buttonColorGained(percent);
    }//GEN-LAST:event_percentMouseEntered

    private void percentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentMouseExited
        buttonColorLost(percent);
    }//GEN-LAST:event_percentMouseExited

    private void ceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceButtonMouseClicked
        
    }//GEN-LAST:event_ceButtonMouseClicked

    private void ceButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ceButtonFocusGained
       
    }//GEN-LAST:event_ceButtonFocusGained

    private void percentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentKeyPressed
        
    }//GEN-LAST:event_percentKeyPressed

    private void percentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentKeyTyped
         
    }//GEN-LAST:event_percentKeyTyped

    private void percentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_percentFocusGained
        
    }//GEN-LAST:event_percentFocusGained

    private void percentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentMouseClicked
       
    }//GEN-LAST:event_percentMouseClicked

    private void percentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentMousePressed
       
    }//GEN-LAST:event_percentMousePressed
                       
    public void zeroRemove()
    {
        if(textArea.getText().equals("0"))
        {
            textArea.setText("");
        }
    }
    public void buttonOperationsColorGained(JButton button)
    {
        button.setBackground(new Color(255, 255, 255));
        button.setForeground(new Color(255, 149, 1));
    }
    public void buttonOperationsColorLost(JButton button)
    {
        
        button.setBackground(new Color(255, 149, 1));
        button.setForeground(new Color(255, 255, 255));
    }
    public void buttonColorGained(JButton button)
    {
        button.setBackground(new Color(217, 217, 217));
        button.setForeground(new Color(0, 0, 0));
    }
    public void buttonColorLost(JButton button)
    {
        
        button.setBackground(new Color(166, 166, 166));
        button.setForeground(new Color(0, 0, 0));
    }
    public void buttonNumbersColorGained(JButton button)
    {
        button.setBackground(new Color(115, 115, 115));
        button.setForeground(new Color(255, 255, 255));
    }
    public void buttonNumbersColorLost(JButton button)
    {
        
        button.setBackground(new Color(51, 51, 51));
        button.setForeground(new Color(255, 255, 255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Calc().setVisible(true);
//            }
//        });
        //</editor-fold>
       

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Calc().setVisible(true);
//            }
//        });
    
    new Calc().setVisible(true);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addition;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton cButton;
    private javax.swing.JButton calculation;
    private javax.swing.JButton ceButton;
    private javax.swing.JButton comma;
    private javax.swing.JButton delButton;
    private javax.swing.JButton division;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton multiplication;
    private javax.swing.JButton percent;
    private javax.swing.JButton raising;
    private javax.swing.JButton root;
    private javax.swing.JButton sign;
    private javax.swing.JButton substraction;
    private javax.swing.JTextField textArea;
    private javax.swing.JTextField textArea1;
    // End of variables declaration//GEN-END:variables
}
